import os
import streamlit as st
from dotenv import load_dotenv
import google.generativeai as genai

# -----------------------------
# 1. Load API key from .env
# -----------------------------
load_dotenv()
API_KEY = os.getenv("GOOGLE_API_KEY")

if not API_KEY:
    try:
        # Try loading from streamlit secrets if .env is missing (good for deployment)
        API_KEY = st.secrets["GOOGLE_API_KEY"]
    except:
        pass

if not API_KEY:
    st.error("🔑 GOOGLE_API_KEY is missing. Please create a .env file with GOOGLE_API_KEY=your_key_here")
    st.stop()

genai.configure(api_key=API_KEY)

# You can change model name if needed
MODEL_NAME = "gemini-flash-lite-latest"
model = genai.GenerativeModel(MODEL_NAME)

# -----------------------------
# 2. Streamlit Page Config
# -----------------------------
st.set_page_config(
    page_title="Goal Planner Agent",
    page_icon="🧠",
    layout="centered",
)

st.title("🧠 Goal Planner Agent")
st.write(
    "Give me a goal, and I’ll break it into small, smart steps for you.\n"
    "This is your first *Agentic AI*: it **reasons** instead of just answering."
)

# -----------------------------
# 3. User Inputs
# -----------------------------
goal = st.text_input(
    "🎯 Enter your goal (e.g., 'Prepare for AI exam', 'Start a YouTube channel')",
    ""
)

persona = st.selectbox(
    "Who are you?",
    [
        "College student",
        "Working professional",
        "Beginner in tech",
        "Custom description",
    ],
)

if persona == "Custom description":
    persona = st.text_input(
        "Describe yourself in one line (e.g., '2nd year AIML student with basic Python'):",
        ""
    )

num_steps = st.slider(
    "How many steps do you want?",
    min_value=3,
    max_value=10,
    value=5,
)

include_schedule = st.checkbox("🗓️ Include a simple timeline (e.g., Week 1, Week 2)?", value=True)
tone = st.selectbox(
    "Tone of the plan",
    ["Simple & friendly", "Motivational", "Very detailed", "Strict & disciplined"]
)

# -----------------------------
# 4. Build the system-style prompt
# -----------------------------
def build_prompt(goal: str, persona: str, num_steps: int, include_schedule: bool, tone: str) -> str:
    schedule_part = (
        "Add a simple timeline like Week 1, Week 2, etc. "
        "Make sure the schedule is realistic for a student.\n"
        if include_schedule
        else "Do NOT mention weeks or dates. Just give steps.\n"
    )

    tone_instructions = {
        "Simple & friendly": "Use simple, friendly language. Talk like a kind senior helping a junior.",
        "Motivational": "Sound encouraging and supportive. Add 1-2 motivational lines.",
        "Very detailed": "Make each step detailed with sub-bullets.",
        "Strict & disciplined": "Sound strict and disciplined, like a serious coach.",
    }

    tone_text = tone_instructions.get(tone, "")

    prompt = f"""
You are a structured planning assistant for an AI bootcamp.

User persona: {persona or "Not specified"}
User goal: {goal}

Your job:
- Break this goal into exactly {num_steps} clear, ordered steps.
- Make the steps realistic and actionable.
- Each step should be 1-2 sentences max (unless user wants very detailed).
- Use numbered list format (1., 2., 3., ...).

{schedule_part}
{tone_text}

Format:
- Start with a one-line summary of the goal.
- Then give the numbered steps.
- End with one short encouragement line.

Now create the plan.
"""
    return prompt.strip()

# -----------------------------
# 5. Generate Plan
# -----------------------------
if st.button("✨ Generate Plan"):

    if not goal.strip():
        st.warning("Please enter a goal first 🙂")
    else:
        with st.spinner("Thinking and planning your steps... 🤔"):
            try:
                prompt = build_prompt(goal, persona, num_steps, include_schedule, tone)
                response = model.generate_content(prompt)
                text = response.text

                st.subheader("🧩 Your AI-Generated Plan")
                st.write(text)

                st.caption(
                    "⚠️ This plan was generated by an AI agent. "
                    "Always use your judgment and adjust steps to your real life."
                )

            except Exception as e:
                st.error(f"Oops! Something went wrong: {e}")
                st.info("Check your API key, internet connection, or try again in a few seconds.")

# -----------------------------
# 6. Sidebar: Explanation
# -----------------------------
with st.sidebar:
    st.header("📚 What is this app?")
    st.write(
        "- This is your **Day 1 Agentic AI mini-project**.\n"
        "- You give a **goal**, the AI **reasons** and turns it into steps.\n"
        "- This is the start of building **agents** that can plan and act."
    )

    st.markdown("---")
    st.subheader("🔐 Safety")
    st.write(
        "✅ Your API key is loaded from `.env` (not hard-coded).\n"
        "✅ Do NOT share your key or push `.env` to GitHub.\n"
        "✅ This app does not store your inputs."
    )

    st.markdown("---")
    st.subheader("🧠 Next Step")
    st.write(
        "On Day 2, we’ll give this agent **memory** and the ability to use **external tools** (like APIs)."
    )
